
import java.util.ArrayList;
import java.util.stream.Collectors;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class DilwsiSimmetoxisUI extends javax.swing.JFrame {

    private DilwsiSymmetoxisController dsc;
    Client client1 = new Client("15-10-2018","15-10-2019",2);
    
    public DilwsiSimmetoxisUI(DilwsiSymmetoxisController dsc) {
        this.dsc=dsc;
        initComponents();
        jTable1.setVisible(false);
    }
   
    
//    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Δήλωση Συμμετοχής");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ArrayList<Program> progs = dsc.getPrograms(client1);
        jTable1.setVisible(true);
        
       
         
        String col[] = {"Τίτλος","Αίθουσα","Ημέρα", "Χωρητικότητα", "Ώρα"};
        while(jTable1.getRowCount() > 0){
            ((DefaultTableModel) jTable1.getModel()).removeRow(0);
        }

        DefaultTableModel TableModel = (DefaultTableModel) jTable1.getModel();

        TableModel.setColumnIdentifiers(col);
        for (int i =0; i<progs.size();i++){
            String[] kati = covert(progs,i);
            TableModel.addRow(kati);
        }
   
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

  
    

    private String[] covert(ArrayList<Program> result, int i) {
    
        int aith=  result.get(i).getAithousa();
        String m = result.get(i).getDay();
        String n = result.get(i).getTitlos();
        int cap= result.get(i).getCapacity();
        int time= result.get(i).getTime();
        String[] table= {n+"",aith+"",m,cap+"",time+""};
        
        return table;  
    }
}

   


